version: "3.8"
networks:
  backend:
  frontend:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    tty: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      BUNDLE_GEMFILE: /app/Gemfile
      DB: postgresql
      DB_HOST: db_postgresql
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      APPLICATION_NAME: app_rails_4_to_5
      JWT_KEY: wDWZiphGmJwEvNEYgMpxNdR8eRN254
      RAILS_ENV: development
      PORT: 3000
    networks:
      - backend
      - frontend
    ports:
      - "3000:3000"
    depends_on:
      - db_postgresql
      - redis
    command: bin/docker-dev-start-web.sh
  redis:
    restart: always
    image: redis:7-alpine
    container_name: redis_container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    networks:
      - backend
  db_postgresql:
    container_name: postgresql_container
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  bundle:
  postgres_data:
